name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: html_test
      id: html_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: html_test
        setup-command: nim install htmlhint
        command: htmlhint --config tests/.htmlhintrc '**/*.html'
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HTML_TEST_RESULTS: "${{steps.html_test.outputs.result}}"
      with:
        runners: html_test
